const Map<String, String> strings = {
  'app_name': 'E-Market',
  'login': 'Accedi',
  'register': 'Registrati',
  'email': 'E-mail',
  'password': 'Password',
  'name': 'Nome',
  'company_name': 'Nome azienda',
  'phone': 'Telefono',
  'whatsapp': 'WhatsApp',
  'website': 'Sito web',
  'address': 'Indirizzo',
  'country': 'Paese',
  'user_type': 'Tipo di utente',
  'importer': 'Importatore',
  'exporter': 'Esportatore',
  'submit': 'Invia',
  'cancel': 'Annulla',
  'search': 'Cerca',
  'home': 'Home',
  'products': 'Prodotti',
  'points': 'Punti',
  'balance': 'Saldo',
  'unlock': 'Sblocca',
  'unlocked': 'Sbloccato',
  'loading': 'Caricamento...',
  'error': 'Errore',
  'retry': 'Riprova',
  'logout': 'Esci',
  'profile': 'Profilo',
  'analysis': 'Analisi',
  'competitive_analysis': 'Analisi competitiva',
  'pestle_analysis': 'Analisi PESTLE',
  'swot_analysis': 'Analisi SWOT',
  'market_plan': 'Piano di mercato',
  'insufficient_balance': 'Saldo insufficiente',
  'unlock_cost': 'Costo di sblocco',
  'credits': 'Crediti',
  'desktop_only_title': 'Solo desktop',
  'desktop_only_message': 'La versione mobile non è pronta. Utilizza questa app solo da desktop.',
};
