const Map<String, String> strings = {
  'app_name': 'E-Market',
  'login': 'Login',
  'register': 'Register',
  'email': 'Email',
  'password': 'Password',
  'name': 'Name',
  'company_name': 'Company Name',
  'phone': 'Phone',
  'whatsapp': 'WhatsApp',
  'website': 'Website',
  'address': 'Address',
  'country': 'Country',
  'user_type': 'User Type',
  'importer': 'Importer',
  'exporter': 'Exporter',
  'submit': 'Submit',
  'cancel': 'Cancel',
  'search': 'Search',
  'home': 'Home',
  'products': 'Products',
  'points': 'Points',
  'balance': 'Balance',
  'unlock': 'Unlock',
  'unlocked': 'Unlocked',
  'loading': 'Loading...',
  'error': 'Error',
  'retry': 'Retry',
  'logout': 'Logout',
  'profile': 'Profile',
  'analysis': 'Analysis',
  'competitive_analysis': 'Competitive Analysis',
  'pestle_analysis': 'PESTLE Analysis',
  'swot_analysis': 'SWOT Analysis',
  'market_plan': 'Market Plan',
  'insufficient_balance': 'Insufficient Balance',
  'unlock_cost': 'Unlock Cost',
  'credits': 'Credits',
  'desktop_only_title': 'Desktop Only',
  'desktop_only_message': 'Mobile layout is not ready. Please use this app on desktop only.',
};
