const Map<String, String> strings = {
  'app_name': 'E-Market',
  'login': 'Connexion',
  'register': 'S\'inscrire',
  'email': 'E-mail',
  'password': 'Mot de passe',
  'name': 'Nom',
  'company_name': 'Nom de l\'entreprise',
  'phone': 'Téléphone',
  'whatsapp': 'WhatsApp',
  'website': 'Site Web',
  'address': 'Adresse',
  'country': 'Pays',
  'user_type': 'Type d\'utilisateur',
  'importer': 'Importateur',
  'exporter': 'Exportateur',
  'submit': 'Soumettre',
  'cancel': 'Annuler',
  'search': 'Rechercher',
  'home': 'Accueil',
  'products': 'Produits',
  'points': 'Points',
  'balance': 'Solde',
  'unlock': 'Déverrouiller',
  'unlocked': 'Déverrouillé',
  'loading': 'Chargement...',
  'error': 'Erreur',
  'retry': 'Réessayer',
  'logout': 'Déconnexion',
  'profile': 'Profil',
  'analysis': 'Analyse',
  'competitive_analysis': 'Analyse concurrentielle',
  'pestle_analysis': 'Analyse PESTLE',
  'swot_analysis': 'Analyse SWOT',
  'market_plan': 'Plan de marché',
  'insufficient_balance': 'Solde insuffisant',
  'unlock_cost': 'Coût de déverrouillage',
  'credits': 'Crédits',
};
