const Map<String, String> strings = {
  'app_name': 'E-Market',
  'login': 'Iniciar sesión',
  'register': 'Registrarse',
  'email': 'Correo electrónico',
  'password': 'Contraseña',
  'name': 'Nombre',
  'company_name': 'Nombre de la empresa',
  'phone': 'Teléfono',
  'whatsapp': 'WhatsApp',
  'website': 'Sitio web',
  'address': 'Dirección',
  'country': 'País',
  'user_type': 'Tipo de usuario',
  'importer': 'Importador',
  'exporter': 'Exportador',
  'submit': 'Enviar',
  'cancel': 'Cancelar',
  'search': 'Buscar',
  'home': 'Inicio',
  'products': 'Productos',
  'points': 'Puntos',
  'balance': 'Saldo',
  'unlock': 'Desbloquear',
  'unlocked': 'Desbloqueado',
  'loading': 'Cargando...',
  'error': 'Error',
  'retry': 'Reintentar',
  'logout': 'Cerrar sesión',
  'profile': 'Perfil',
  'analysis': 'Análisis',
  'competitive_analysis': 'Análisis competitivo',
  'pestle_analysis': 'Análisis PESTLE',
  'swot_analysis': 'Análisis SWOT',
  'market_plan': 'Plan de mercado',
  'insufficient_balance': 'Saldo insuficiente',
  'unlock_cost': 'Costo de desbloqueo',
  'credits': 'Créditos',
};
