const Map<String, String> strings = {
  'app_name': 'إي ماركت',
  'login': 'تسجيل الدخول',
  'register': 'التسجيل',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'name': 'الاسم',
  'company_name': 'اسم الشركة',
  'phone': 'الهاتف',
  'whatsapp': 'واتساب',
  'website': 'الموقع الإلكتروني',
  'address': 'العنوان',
  'country': 'الدولة',
  'user_type': 'نوع المستخدم',
  'importer': 'مستورد',
  'exporter': 'مصدر',
  'submit': 'إرسال',
  'cancel': 'إلغاء',
  'search': 'بحث',
  'home': 'الرئيسية',
  'products': 'المنتجات',
  'points': 'النقاط',
  'balance': 'الرصيد',
  'unlock': 'فتح',
  'unlocked': 'مفتوح',
  'loading': 'جاري التحميل...',
  'error': 'خطأ',
  'retry': 'إعادة المحاولة',
  'logout': 'تسجيل الخروج',
  'profile': 'الملف الشخصي',
  'analysis': 'التحليل',
  'competitive_analysis': 'التحليل التنافسي',
  'pestle_analysis': 'تحليل بيستل',
  'swot_analysis': 'تحليل سوات',
  'market_plan': 'خطة السوق',
  'insufficient_balance': 'رصيد غير كافٍ',
  'unlock_cost': 'تكلفة الفتح',
  'credits': 'نقاط',
};

